### ISSUE TITLE
support CBS.log

### ISSUE THREAD

**Issue by Vaquero84** [mrodalgaard/language-log#2]
The windows CBS.log file is currently not color coded by language-log. This is a file that results from windows system scans like "sfc /Scannow". It is usually found under "C:\Windows\Logs\CBS\CBS.log". It accumulates over time and therefor gets difficult to navigate through.
It'll be great if Warnings were highlighted or any other relevant information (e.g. when failed to repair a component). And what would help navigating through different scan results, is, if the time stamps in front of any line get clustered. So a sudden large difference in the time would mean a new scan was performed and the following time stamps would get another color until a new jump appears, hence forming a cluster.

**Comment by mrodalgaard** [comment]
Basic CBS log support added.

I extracted the immediate important parts, but I might have missed some since I haven't used these logs before.

Regarding the clustering of timestamps with different colors; it's a great idea, but I do not think it can be achieved with language grammar alone. As I see it, Atom grammars are designed for line-to-line analysis 
and blocks like multiple line comment blocks.

At some point I might look at extending this package with some advanced grouping, sorting and filtering. Would you mind opening another issue for the clustering part, with all the info you got?
